### ISSUE TITLE
Vite server 500 crash when using VitePluginHelper.asset

### ISSUE THREAD

**Issue by Erudition** [hmsk/vite-plugin-elm#455]
When I go to add `VitePluginHelper.asset` to my svg path strings in Elm, the server no longer works, and vite crashes with:

```
TypeError: Invalid value used in weak set
    at WeakSet.add (<anonymous>)
    at output (file:///home/adroit/Projects/Minder/node_modules/.pnpm/vite@4.2.1_@types+node@18.15.11/node_modules/vite/dist/node/chunks/dep-79892de8.js:12529:30)
    at Object.error (file:///home/adroit/Projects/Minder/node_modules/.pnpm/vite@4.2.1_@types+node@18.15.11/node_modules/vite/dist/node/chunks/dep-79892de8.js:12571:13)
    at logError (file:///home/adroit/Projects/Minder/node_modules/.pnpm/vite@4.2.1_@types+node@18.15.11/node_modules/vite/dist/node/chunks/dep-79892de8.js:42888:26)
    at viteErrorMiddleware (file:///home/adroit/Projects/Minder/node_modules/.pnpm/vite@4.2.1_@types+node@18.15.11/node_modules/vite/dist/node/chunks/dep-79892de8.js:42902:9)
    at call (file:///home/adroit/Projects/Minder/node_modules/.pnpm/vite@4.2.1_@types+node@18.15.11/node_modules/vite/dist/node/chunks/dep-79892de8.js:48900:7)
    at next (file:///home/adroit/Projects/Minder/node_modules/.pnpm/vite@4.2.1_@types+node@18.15.11/node_modules/vite/dist/node/chunks/dep-79892de8.js:48848:5)
    at call (file:///home/adroit/Projects/Minder/node_modules/.pnpm/vite@4.2.1_@types+node@18.15.11/node_modules/vite/dist/node/chunks/dep-79892de8.js:48913:3)
    at next (file:///home/adroit/Projects/Minder/node_modules/.pnpm/vite@4.2.1_@types+node@18.15.11/node_modules/vite/dist/node/chunks/dep-79892de8.js:48848:5)
    at call (file:///home/adroit/Projects/Minder/node_modules/.pnpm/vite@4.2.1_@types+node@18.15.11/node_modules/vite/dist/node/chunks/dep-79892de8.js:48913:3)
```

But as soon as I take it out and leave it as a plain string, it works fine again.

**Comment by Erudition** [comment]
Edit: just realized this is due to:
`That string should be just a string without any concatenation.`
I'm definitely going to need concatenation, but when I put in a full string url the problem does indeed go away... How can we accomplish this?

**Comment by hmsk** [comment]
Thanks for reporting! Can you provide a reproducible repo?

**Comment by hmsk** [comment]
Thanks for giving the additional detail! I don't know if we can make concatenation possible technically, but at least wanna try to avoid the crash and give a proper guide/warning.
